// netmdl.idl : IDL source for netmdl
//

// This file will be processed by the MIDL tool to
// produce the type library (netmdl.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(C025C3C0-4368-42EC-BB98-205E0E98B0F9),
	version(1.0),
]
library netmdlLib
{
	importlib("stdole2.tlb");
};

